#!/bin/sh

cd $(dirname $0)
source $(dirname $0)/panel_config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PADDING=$((PANEL_HEIGHT+PANEL_TOP))
echo $PADDING
bspc config top_padding $PADDING
bspc control --subscribe > "$PANEL_FIFO" &
echo "T" >  "$PANEL_FIFO" &
conky -c ./panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
    | ./panel_bar \
    | lemonbar \
        -f "$FONT1"\
        -f "$FONT2"\
        -F "$COLOR_FOREGROUND"\
        -B "$COLOR_BACKGROUND"\
        -g  $PANEL_GEOMETRY &
wait

