#! /bin/sh

bspc config -m ^1 top_padding		24
bspc config border_width        5
bspc config window_gap         20

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#c5c8c6'
bspc config presel_border_color '#b5bd68'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#f0c674'
bspc config urgent_border_color '#cc6666'

bspc monitor ^1 -d I II III IV V
bspc monitor ^2 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/panel/panel &
