#! /bin/sh
#
# bar input parser for bspwm  Tuesday, 01 July 2014 22:57

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

function B {
    echo "%{B$2}$1%{B-}"
}

function F {
    echo "%{F$2}$1%{F-}"
}

while read -r line ; do
    case $line in
        S*)
            # conky
            sys_infos="${line#?}"
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused used desktop
                                desk="$(B " $(F $name $ACTIVE_FG) " $ACTIVE_BG)"
                                ;;
                            F*)
                                # focused empty desktop
                                desk="$(B " $(F $name $ACTIVE_FG) " $ACTIVE_BG)"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="$(B " $(F $name $ACTIVE_FG) " $ACTIVE_BG)"
                                ;;
                            o*)
                                # occupied desktop
                                desk="$(B " $(F $name $USED_FG) " $USED_BG)"
                                ;;
                            f*)
                                # free desktop
                                desk="$(B " $(F $name $UNUSED_FG) " $UNUSED_BG)"
                                ;;
                            u*)
                                # urgent desktop
                                desk="$(B " $(F $name $FORE) " $DIMFORE)"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    # printf "%s\n" "%{l} %{F$COLOR1}$(printf "%b" "\ue0a1")%{F-} $(uname -r)%{c} $wm_infos%{r}$sys_infos "
    printf "%s\n" "%{l}$wm_infos%{r}$sys_infos "
done