export PS1="%{[38;05;0;48;05;7m%} %3~ %{[38;05;7;48;05;4m%}⮀%{[00m%}%{[38;05;8;48;05;4m%}%{[00m%}%{[38;05;4m%}⮀ %{[00m%}"

# Fix for screen not working in ssh sessions in termite
#alias ssh='TERM=xterm-color ssh'
export 'FLASK_CONFIG=MySQLStd'

#[ -n "$XTERM_VERSION" ] && transset-df -a -m 0.9 >/dev/null

export PATH="$PATH:$HOME/.bin"
